### ISSUE TITLE
Conteúdos e linguagens

### ISSUE THREAD

**Issue by carvalholeo** [baixada/traducoes#1]
Oi, boa tarde.

Vi no grupo do Baixada Nerd esse repositório e fiquei interessado em contribuir para as traduções. Que tipo de conteúdo deve ser traduzido? Blogposts, documentação de linguagem, vídeos, etc? E ao fazer o PR, deve ser criada alguma estrutura de pastas?

Valeuuu!

**Comment by geovanasilva** [comment]
Oi bom dia,
A ideia é ir traduzindo sob demanda, mas caso tenha sugestões em mente você já pode começar a traduzir e pode ser qualquer coisa, mas eu diria que fica mais interessante livros, artigos e documentações. A estrutura de pastas a ser criada seria assim, primeiro seu segmento então são três pastas ai no mínimo: 

- artigos;
-  livros;
- documentações.

E dentro de cada segmento criamos pastas referentes ao conteúdo em que eles se enquadram, como por exemplo: react, e nessa pasta podemos inserir os arquivos .md referentes de maneira direta, seria legal enumerar e dai fica assim:

/artigos
-- /react
--- 001-artigo-maneiro-de-react.md

Quando se tratar de livros e documentações ficará assim:

/livros
-- /livro-daora
--- /capitulos
---- 001-hello-world
--- /imagens
--- /pdf
--- glossario.md
--- sumario.md

Acredito que dessa maneira fica bem organizadinho, mas caso queira discutir a respeito não tem problema. Qualquer dúvida é só chamar e obrigada pelo interesse.

Abraços.
